### ISSUE TITLE
Some MFEL3010 questions lack images with necessary info

### ISSUE THREAD

**Issue by estensen** [draperunner/kramster-data#1]
Maybe images are not parsed correctly from the pdfs?

<img width="1159" alt="screenshot 2018-11-29 12 58 56" src="https://user-images.githubusercontent.com/9142800/49220492-a5804d00-f3d6-11e8-97e1-90ec88934598.png">

**Comment by draperunner** [comment]
Thanks for reporting this! I will look into it. I see that the numbers (here: `9. ` and `a)`, `b)`, etc. are included as well. They are not supposed to.

**Comment by draperunner** [comment]
I went throught the exams and fixed a lot of questions with missing information. Open this issue again if you find anything else :)
